### ISSUE TITLE
Nixpkgs package

### ISSUE THREAD

**Issue by Rucadi** [ceritium/flatito#8]
I've created this PR: https://github.com/NixOS/nixpkgs/pull/299177 so that flatito can be installed from nixpkgs.

Nice work with the tool 💯 Works fine so far.

**Comment by ceritium** [comment]
Many thanks. I don't have experience with NixOS or nixpkgs; do I have to do something? What happens whenever I want to release a new version?

**Comment by Rucadi** [comment]
I added myself as a maintainer of the package so I can update the package more easily,

but to update it, you have to create a PR.
The first you should modify is:

 flatito.source = {
        remotes = [ "https://rubygems.org" ];
        sha256 = "9f5a8f899a14c1a0fe74cb89288f24ddc47bd5d83ac88ac8023d19b056ecb50f";
        type = "gem";
      };

to point to your new version of flatito.

Update the version from:
 version = "0.1.1";


And update the hash:

source.sha256 = "sha256-n1qPiZoUwaD+dMuJKI8k3cR71dg6yIrIAj0ZsFbstQ8=";

(basically, leave the hash empty and if you try to build the package with nix, it will tell you the hash it got)

It is difficult to explain exactly all the steps but:

if you already have nix with flakes setup:

```
git clone [your nixpkgs fork]
cd nixpkgs
--edit what I mentioned--
nix build .#flatito
```

It'll try to generate the package and mention any error found.

Once the command finishes successfully, you'll have a symlinked folder called result which contains the app ready to test.

**Comment by Rucadi** [comment]
Flatito was merged to Nixpkgs master today with commit https://github.com/NixOS/nixpkgs/commit/d9e67131c2f07c11d31fa02bc52b121fe85e5498 !

It can be easily tested doing:
nix run nixpkgs/master#flatito

which will directly download and run flatito 👍 

This makes it easier to use and test the application and to include as a system package 😊

**Comment by ceritium** [comment]
Many thanks, it works great, I will update the README.md in the following days.
